### ISSUE TITLE
Implement fmt.Stringer.

### ISSUE THREAD

**Issue by hsblhsn** [bnkamalesh/currency#1]
Hi @bnkamalesh, thank you for this awesome package. It would be really nice if `currency.Currency` implements `fmt.Stringer` interface. At this moment it has a string method, but it has a signature like below:

```go
func (c *Currency) String(prefixSymbol bool) string
```

To implement `fmt.Stringer` the string method must have the signature:

```go
func (c *Currency) String() string
```

If the Currency type implements `fmt.Stringer`, we will not need to call `c.String(true|false)`, every-time we want to get the formatted string output.

So I propose, the `Currency` should have method signatures like this

```go
func (c *Currency) SetSymbol(symbol string)
func (c *Currency) String() string
```

or, 

```go
func (c *Currency) PrefixSymbol(symbol string) string
func (c *Currency) String() string
```

This is just a concept, I am confident that you will find even better way out.

**Comment by bnkamalesh** [comment]
https://github.com/bnkamalesh/currency/pull/3 
https://github.com/bnkamalesh/currency/pull/2

@hsblhsn These PRs should give you lot more control over generating string.
